spring:
  application:
    name: ogcnice-api

  datasource:
    url: jdbc:postgresql://localhost:5432/nice_fc
    username: ${DB_USERNAME:nice}
    password: ${DB_PASSWORD:nice}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

logging:
  level:
    com.ogcnice.api: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

server:
  port: 8080
  servlet:
    context-path: /api
